#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to install nginx

apt-get update
apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
